"""add created_at to fruit

Revision ID: 63ef11aa20c3
Revises:
Create Date: 2025-04-12 08:15:55.948002

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "63ef11aa20c3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("fruit", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.execute("UPDATE fruit SET created_at = CURRENT_TIMESTAMP")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fruit", "created_at")
    # ### end Alembic commands ###
